### ISSUE TITLE
Remove tags with 0 uses

### ISSUE THREAD

**Issue by Ayutac** [shish/shimmie2#1012]
**Is your feature request related to a problem? Please describe.**
Sometimes tags are miss-typed but after correcting them, the miss-typed tag is still in the database. These empty tags are also shown as suggestions when entering a tag.

**Describe the solution you'd like**
Functionality to clear empty tags from the DB. If it is a simple SQL Script, my admin can execute it, but we are not sure if that breaks anything.

**Describe alternatives you've considered**
- Delete tags from the database when they reach 0 uses
- Don't show tags that have 0 uses as suggestions

**Comment by shish** [comment]
Tags with 0 uses showing up in autocomplete was a bug, fixed in 1b6d8540a5af2625d9ee7c9a71628fb82175612e

For deleting unused tags - in the `tag_tools` extension there is a "Recount Tag Use" button which ensures tags are _actually_ unused (there have in the past been issues which caused the counter to get out of sync), and then deletes any that are at 0 after being recounted

**Comment by Ayutac** [comment]
Wasn't aware it did that! Thanks!
