### ISSUE TITLE
Shimmie vulnerable to XSS

### ISSUE THREAD

**Issue by 153** [shish/shimmie2#401]
Most shimmie implementations on the web are vulnerable to XSS attacks in the form of 
">&lt;script>alert('attacked')</script&gt;
or something of the sort entered in the search box. 

I point you to http://shimmie.katawa-shoujo.com/ for reference.

**Comment by The-Excel** [comment]
My install labeled version 2.5.3 checked out from master in January 2015 is vulnerable. https://whatistheexcel.com/wooobooru/post/list

**Comment by shish** [comment]
@The-Excel the only place I see that code appearing without being escaped is within a block of code marked `<script type="text/rocketscript">` -- as far as I'm aware that is not shimmie code. Perhaps a third-party extension or custom theme is the problem? :S

**Comment by The-Excel** [comment]
That is probably the Rocket Loader extension in CloudFlare. I turned it off and I'm still seeing the XSS, except that the page doesn't fully load before the <script> is executed.

These are the extensions I have enabled in extensions.conf.php: `admin,arrowkey_navigation,blocks,blotter,bookmarks,browser_search,danbooru_api,downtime,favorites,google_analytics,handle_video,home,image_hash_ban,ipban,mass_tagger,not_a_tag,pm,pools,qr_code,random_image,random_list,regen_thumb,report_image,rss_images,site_description,tag_categories,tag_history,tagger,tips,wiki`

The theme I'm using is the default Lite with custom CSS.

**Comment by jgen** [comment]
Ah, you're right! There actually is a vulnerability in the `arrowkey_navigation` extension. :(

(I don't think anyone had it enabled, which is why nobody could reproduce the problem.)

I've submitted a pull request  #481 to fix this. (its a one line fix)

**Comment by The-Excel** [comment]
Disabling the extension closes the vulnerability. I'll wait for a merge to re-enable it.

**Comment by jgen** [comment]
First, sorry for not catching this problem sooner (when it was first reported).

Secondly, Thank you for bringing more attention to this issue - and thanks for providing details on the matter. It definitely helped out. :+1: 

Aside: I think perhaps this issue should stay open until the fix is merged into master and/or a tagged release.

**Comment by jgen** [comment]
Looks like @Shish already merged the fix into master and created a new tagged release: https://github.com/shish/shimmie2/tree/v2.5.4

Thanks!

**Comment by shish** [comment]
(As an aside, yeah, keeping bugs open until fixed in master seems like a good idea)

**Comment by The-Excel** [comment]
Have the rest of the default optional extensions been similarly audited?

**Comment by shish** [comment]
Depends what you mean by audited? I'm not aware of anyone going through the code line-by-line looking for this issue specifically; but it is a known weakness of PHP that people keep in mind while writing and reviewing code, and shimmie has things in place to deal with it as best as possible (at least, as best as possible while continuing to use the fundamentally flawed PHP language D: )

**Comment by The-Excel** [comment]
With something this serious, I'm not sure I can trust the extensions I haven't turned on that I might want to use one day.

**Comment by shish** [comment]
I'm afraid I don't follow your thinking or see what you're getting at :S

**Comment by The-Excel** [comment]
I think I'm just going to have to run this test every time I turn an extension on.

**Comment by jgen** [comment]
I think that what he/she is getting at is that it is entirely possible there are other XSS vulnerabilities in other Shimmie extensions.

**Comment by shish** [comment]
This seems kind of like finding a flea on a dog's left ear, and then deciding not to trust any left ears, always making sure to check the left ear of every dog you meet before petting it... It's not /wrong/, but it is a small part of a big picture; and even if you check the whole dog (as we have done, twice), it's still possible to have missed a flea that was well camouflaged.

In non-metaphorical terms - testing for this one issue *might* protect you from this one issue (emphasis on "might", because you can only ever say "I have not found a bug", not "there is no bug"), but even if it does, there are an infinite number of other potential problems; having backups and keeping up to date is likely to be a more effective approach to keeping your data safe~

(This advice applies to all software, not just Shimmie)

(I am doing my best to avoid coming across negatively -- a third set of eyes *is* a good thing, I just don't want to get anyone's hopes up that security is as simple as "we've checked this thing, it passed, therefore there are zero bugs, guaranteed" v_v)
