### ISSUE TITLE
Scrutinize ip address

### ISSUE THREAD

**Issue by lordkitsuna** [shish/shimmie2#472]
any chance someone can add an option to check for "forwarded for" headers so that when using something like say cloudflare we can still do ipbans and such?

**Comment by shish** [comment]
Erk, somehow I completely missed this, sorry >_<

It would be possible to do at the shimmie level; but I've found that it's more effective to do at the web-server level since then /everything/ benefits from it. Closing for now as it's been so long, but feel free to re-open if you're still there and either want help configuring a webserver or making shimmie do it.
