### ISSUE TITLE
Webm Thumbnail Fix

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#486]
Hello is their anyway to make the webm thumbnail look better it all comes out with a 250x250 box this looks odd the webms that are long on the sides makes it look smashed any way to get a better thumbnail like danbooru or gelbooru?

**Comment by jgen** [comment]
Hello,
Thanks for the feedback.

If you take a look under the **"Board Config"** section, you can try the option called:
_"Ignore aspect ratio when creating thumbnails"_

(This was added as part of #468)

You will need to have a newer version of FFmpeg for this to work though.

This would help so that the thumbnails are not always forced to 250x250 (or whatever your current setting is) and they should be in the same aspect ratio as the video itself.

**Comment by shish** [comment]
Cleaning out old bug reports, this should be fixed since a while ago
