### ISSUE TITLE
Pay for New theme?

### ISSUE THREAD

**Issue by i2plover** [shish/shimmie2#508]
Is it possible for me to pay a designer (or rather is a designer who will) make a new theme for Shimmie2 with material design? So that it's up to date, and also mobile friendly at last?

I would suggest using materializecss.com

I'm willing to throw into the pot $20

**Comment by shish** [comment]
I don't know any designers myself, but I would be happy for that to happen, and can assist with the backend bits

**Comment by i2plover** [comment]
I can try to do it myself if I knew how to get around the shimmie2 structure. It's a bit weird from what I saw inside the php files. 

So yes, any help to guide me in the right direction would be awesome! :+1:

**Comment by i2plover** [comment]
How can I edit the navigation links/the html blocks (left, right)?
How would I move the sidebar from the left to the right? 
How would I edit the "home page" look (the one with the counter on the front) 

Really, I'm kinda asking for where would I find the place to edit to do these things. Like what Php files should I edit to accomplish these things?

**Comment by shish** [comment]
The main place to start would be to copy "themes/warm" to eg "themes/material" (using "warm" as an example because it shows how to customise - if you started with default then you'd only see how to leave things as default); then in that directory

- layout.class.php contains the overall layout (header, footer, navigation, main page elements)
- themelet.class.php contains various common elements (look at `core/basethemelet` to see all the functions that you can override)
- you can customise specific extensions by creating `themes/material/extension_name.theme.php` and editing there (eg if you want to customise `ext/home/theme.php`'s HomeTheme, you would make `themes/material/home.theme.php` which contains `class CustomHomeTheme extends HomeTheme {...}`)

The general idea with shimmie is that each extension will supply a set of "blocks" (a title, a bunch of HTML to show, and hints as to where on the page it belongs) then the `layout.class.php` will take care of arranging the blocks.

Editing the navigation would be in each extension

Switching sidebar from left to right would probably be a combination of changing the HTML in `layout.class.php` and the CSS in `style.css`

The home page with the counter is the "home" extension, whose theme can be customised by creating `themes/material/home.theme.php` and putting in there a class which extends the default `ext/home/theme.php`

**Comment by i2plover** [comment]
Ugh.. Gonna take some time If I have to make it myself..
I'm still willing to pay someone else to do it, and it's open if you can! :+1: Post here if interested. 
Again, read first post to learn more.

**Comment by dali99** [comment]
Maybe you could add the $20 to the [bountysource page](https://www.bountysource.com/issues/26588497-pay-for-new-theme)

**Comment by i2plover** [comment]
@dali99 Done! :+1: https://www.bountysource.com/issues/26588497-pay-for-new-theme
But of course I don't want something thrown together and not easy to work with. Again I suggest using the materializecss.com since it's already compiled and just need to frame around that. It has to be mobile friendly for phones and tablets too.

**Comment by i2plover** [comment]
I could see something similar to this (https://www.materialup.com/posts/online-grocery-store) with the sidebar on the left when pulled out on mobile, or the menu button at the top left. They could search the tags with the search bar of course. All the images have z-depth to them, and also have animations like all material design does. I would suggest using animation.css and wow.js to add the animations easily.

**Comment by dali99** [comment]
I am not a php developer, so I would need some help in figuring out how some parts of the application works. I'm currently reading up on the docs to see what I can learn from it, and I'll ask here if I have any questions (if that's okay). This will probably take a long time though, so the more people we could get to help out the better.

**Comment by i2plover** [comment]
What can we use to collab and work together on this project? I'm alright with Php coding so I may can help with that side.

**Comment by JarJak** [comment]
@shish how about creating some tutorials about how to create own theme / extension?

**Comment by dali99** [comment]
@i2plover That would be great. We could use github. I've made a fork at https://github.com/dali99/shimmie2 where we could make the designs in https://github.com/dali99/Material-Shimmie-Thmeme dynamic.

I've only made /home as of now, and I would like some feedback on what to change:

![screenshot_2015-09-25-07-34-17](https://cloud.githubusercontent.com/assets/990767/10095359/86bd0184-6369-11e5-85ee-4b00f803e840.png)
![screenshot_2015-09-25-07-35-46](https://cloud.githubusercontent.com/assets/990767/10095363/8a02c1a8-6369-11e5-85fe-1dad09d34d3e.png)

I'm not quite happy with the default hamburger icon, so I'll probably replace it with an animated one. I also feel like it's a bit too close to the left edge.

**Comment by shish** [comment]
I am liking the idea of a slide-out menu for eg the user block (the place where "My Profile" / "Private Messages" / "Log Out" are). I wonder if it would be too much to put /all/ the sidebar blocks there, accordion style[1]... (Or maybe most of them there, but cut out things like the "recent comments" sidebar bit since we can just link to /comments/list, and cut out Prev / Next since those are part of the main part of the page already)

[1] Like https://jqueryui.com/accordion/ , though not necessarily using that code

**Comment by dali99** [comment]
@shish oh yeah definetly, things like random image and comments do not belong in the pullout navbar.
I'm also thinking we should keep the sitewide navigation in the sidebar similar to how *warm* keeps its navigation on the main site.

I'm thinking we should remove "prev and next" while putting the search bar in the blue field at the top where the hamburger icon is.

When it comes to the acordions, Materialize.css have ["Collapsibles"](http://materializecss.com/collapsible.html)

**Comment by CrandellWS** [comment]
https://www.youtube.com/watch?v=aLnKwCup2A0

https://www.youtube.com/watch?v=fBJS_jYdWqg

Work in progress...

**Comment by dali99** [comment]
@CradellWS welcome aboard! I'm happy this has gotten some more traction from other designers.

I didn't even know Google had anything but the material design guidelines, even though I've seen material design lite. I've checked it out and it sure is much better documented.

I hope we can be partners in this project or "steal" ideas from each other at the very least.

For me the most important thing will be that this project is finished and that it looks great.

**Comment by CrandellWS** [comment]
@dali99 I have been working based on some of  the ideas mentioned here. 

You said:
> thinking we should remove "prev and next" while putting the search bar in the blue field at the top where the hamburger icon is.

I used a waterfall header that has the prev / next in lower part of the top bar and is hidden when scrolling: 
![header](https://cloud.githubusercontent.com/assets/5300522/10718008/a870457e-7b3e-11e5-82ad-3b5a8b2bd0f3.PNG)
![header2](https://cloud.githubusercontent.com/assets/5300522/10718009/a873a368-7b3e-11e5-93c0-c5ffa7cc5a61.PNG)

Should also mention most testing is done on emulators and it seems the "hamburger" and the search icons are not showing on Iphone version =< 5. Also does not work on my Amazon Fire phone.  Though it does seem to work with all the Google Play Android phones...idk will have to figure it out though.


For me it is another item for a portfolio and hopefully a monetary bounty.

**Comment by CrandellWS** [comment]
@dali99  
>things like random image and comments do not belong in the pullout navbar.
I'm also thinking we should keep the site wide navigation in the sidebar similar to how warm keeps its navigation on the main site.

@shish
>(Or maybe most of them there, but cut out things like the "recent comments" sidebar bit since we can just link to /comments/list, and cut out Prev / Next since those are part of the main part of the page already)

Navigation I think should be done like shown https://github.com/shish/shimmie2/issues/508#issuecomment-150976841  

For some extras like QR code should be in a right side column that falls beneath the main content for smaller screens? let me do a couple quick example screen shots...brb

**Comment by CrandellWS** [comment]
So I have not figured out how to reorder cells using mdl-cell--order-N see-> https://github.com/google/material-design-lite/tree/master/src/grid#configuration-options

Not sure why so for now I will use a right side column and left side drawer

**Comment by CrandellWS** [comment]
What Should go into the drawer?

**Comment by CrandellWS** [comment]
Screen shots:

![layout](https://cloud.githubusercontent.com/assets/5300522/10718948/7f1972b6-7b54-11e5-8a73-71ced20c3ddb.png)

![layout2](https://cloud.githubusercontent.com/assets/5300522/10718951/7f1cbf2a-7b54-11e5-99d0-0e1046d08784.png)

![layout3](https://cloud.githubusercontent.com/assets/5300522/10718949/7f1b83f8-7b54-11e5-8b41-e7b4a3224174.png)

![layout4](https://cloud.githubusercontent.com/assets/5300522/10718950/7f1b7ba6-7b54-11e5-84fe-278879c3314f.png)

**Comment by dali99** [comment]
@CrandellWS I really like the idea of putting the prev/next in a waterfall menu.

Let me post some screenshots of my work till now as well.
![screenshot_2015-10-26-07-08-58](https://cloud.githubusercontent.com/assets/990767/10722437/8ce145a2-7bb0-11e5-85a1-7a2775e37d59.png)
![screenshot_2015-10-26-07-08-29](https://cloud.githubusercontent.com/assets/990767/10722435/8cde568a-7bb0-11e5-8d12-1f375c17ace1.png)
![screenshot_2015-10-26-07-07-25](https://cloud.githubusercontent.com/assets/990767/10722436/8ce08018-7bb0-11e5-91fb-850a5e99a090.png)

One of the hardest issues I'm facing currently is how I'm going to deal with images of different aspect ratios. Do you have any suggestions? I was thinking of maybe forcing all the images to grids, allowing tall images to take up two slots creating something like this.

![4c7m3gyf](https://cloud.githubusercontent.com/assets/990767/10722553/981cd2dc-7bb1-11e5-94bd-7e93871aefcb.png)

But I'm honestly not sure how to even start if I'm going to do that.

**Comment by CrandellWS** [comment]
@dali99 I like what you have and honestly I have not started on the image view yet because I want to sort out the layout first... I have some new screenshots. 

You said 

> One of the hardest issues I'm facing currently is how I'm going to deal with images of different aspect ratios. Do you have any suggestions? I was thinking of maybe forcing all the images to grids, allowing tall images to take up two slots creating something like this.

I am sure there is a way to get the aspect ratio and make that happen problematically but not sure the results will be as desired.  I think fitting the image to a square  may be easier, anyhow that is what I will do at first regardless then I will consider doing something like what you suggest.

Perhaps when height is at least double width then use 2 vertices and when width is at least double height use 2 horizontals. Again this is doable but I will stick to 1 image per square at first. 

So I think what I have now is better for view end users because you can move the left column to where you want in the examples see the buttons top,right,bottom,left:

<img src="https://cloud.githubusercontent.com/assets/5300522/10722913/e1fe1d14-7b8b-11e5-8fa9-69dac8756caf.PNG" width="250px"><img src="https://cloud.githubusercontent.com/assets/5300522/10722916/e1ff25a6-7b8b-11e5-8303-f77c58c7b3fb.PNG" width="250px"><img src="https://cloud.githubusercontent.com/assets/5300522/10722918/e20035fe-7b8b-11e5-8356-f414596d4344.PNG" width="250px"><img src="https://cloud.githubusercontent.com/assets/5300522/10722917/e1ff3424-7b8b-11e5-862e-e57b333a2d0f.PNG" width="250px"><img src="https://cloud.githubusercontent.com/assets/5300522/10722914/e1fe662a-7b8b-11e5-9925-64a90050517f.PNG" width="250px"><img src="https://cloud.githubusercontent.com/assets/5300522/10722915/e1fe9c76-7b8b-11e5-98e9-f939785d3a61.PNG" width="250px">

When on top or bottom the "card blocks" in a single row height is equal to the tallest...

### on a different note

Got an issue with the zoom for large images...

```javascript
function zoom(zoom_type) {
	var img = $('.shm-main-image');
	if(zoom_type == "full") {
		img.css('max-width', img.data('width') + 'px');
		img.css('max-height', img.data('height') + 'px');
	}
```

especially on mobiles

So I will replace the function...

**Comment by CrandellWS** [comment]
@dali99  
> I really like the idea of putting the prev/next in a waterfall menu.

I intend to put it back on the recent screenshots it is not there because I have restarted so I will have to re add those changes...

**Comment by dali99** [comment]
@CrandellWS since you are planning on putting the navigation blocks in the main page, what are you going to use the Hamburger menu for?

**Comment by CrandellWS** [comment]
@dali99 not real sure still just becoming familiar with the software only been using it for a couple of days...

**Comment by CrandellWS** [comment]
The base theme is on the development branch see https://github.com/shish/shimmie2/pull/528

**Comment by dali99** [comment]
@shish Is there any reason I should know about why you don't close your <p> tags? for example [here](https://github.com/shish/shimmie2/blob/develop/ext/index/theme.php)

**Comment by muhkuh2005** [comment]
Actually its call'ed "Coding Style Guidelines" ;)
Don't pin to me about which one Shish is using though.

But at work we also follow one that disallows ending PHP-Tags when the
entire file is PHP only.

**Comment by CrandellWS** [comment]
Read about it on php.net 

>**If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script.**

http://php.net/basic-syntax.phptags

**Comment by dali99** [comment]
@muhkuh2005  @CrandellWS  My bad, I was talking about the \<p> tags, looks like markup screwed up my comment.

**Comment by CrandellWS** [comment]
I saw the same thing and wondered myself... most browsers will fix that now days but I think that is bad  practice.

**Comment by i2plover** [comment]
So what's our latest look/update for the theme? :smiley:

**Comment by dali99** [comment]
@i2plover as you can probably see @CrandellWS implementation is merged into development. Mine is still being worked on, designing each page. Have you been able to understand the shimmie source code yet? Cause I think we could possibly start working on porting it over to an actual theme. Rather than just design mock ups :smile:

**Comment by CrandellWS** [comment]
@dali99 What I have done is get a base to work from for individual pages. My focus was not beauty it was usability. Just wanted every plugin to be usable as is from within the template, which is what is done. 

Now individual themes can be created ie `[ext].theme.php` and utilize Google Material Design. A lot of work still to do before it release ready. 

@dali99, you say you are working on individual pages. Would it be helpful if I explain how you can do this using the theme I started? You said, *"I am not a php developer"* maybe we can more closely work together?

**Comment by dali99** [comment]
@CrandellWS Definetly. I'll have to look into Google Material Design rather than using Materializecss though. You'll have to run me through the basics of how this works or else I'm afraid I'll be totally useless.

How about we implement the front page extension first, just as a basic start so I can somewhat understand what's going on.

**Comment by CrandellWS** [comment]
Some links that may help:

 - https://design.google.com/
 - http://www.getmdl.io/

Let me see what I can do for a fast work up on the front page extension.

**Comment by CrandellWS** [comment]
Ok @dali99  I will update this comment as I go. 

The "*front page extension*" is actually called "***home***" you can see it in the ext folder [***`ext/home`***](https://github.com/CrandellWS/shimmie2/tree/develop/ext/home)

**Comment by CrandellWS** [comment]
@dali99 now you just need to adjust the function [body_build](https://github.com/CrandellWS/shimmie2/blob/f22c01ec2e7abc6376e1cda78487c4cbe50e6ece/themes/material/home.theme.php#L88)

But as noted https://github.com/shish/shimmie2/issues/508#ref-commit-f22c01e I thin k the home extension is a bad choice for example, becuase it is using special circumstances. 

Perhaps a different extension choice would be more appropriate to learn from, for what it's worth, normal circumstances.

**Comment by shish** [comment]
FWIW - this seems like the most different type of theme so far, so feel free to make changes to the base classes; eg if the default theme has a single `render_everything()` function and you only want to override a small part, it would be good to split the function up and override an individual bit instead of copy-pasting the whole thing with minor changes :)

**Comment by i2plover** [comment]
Still keeping an eye on the progress of this :+1: Really can't wait to us it!

**Comment by dali99** [comment]
Now, my home extension is almost done as you can see here 
![home almost complete](https://cloud.githubusercontent.com/assets/990767/12022514/b4076992-ad90-11e5-89aa-ee55b28a5d80.PNG)

Now I have some questions. I can't find what's formatting $main_links into \<a class="shm-clink" data-clink-sel="" href="./index.php?q=/post/list"\>Posts\</a\>

You can check it out in [this branch](https://github.com/dali99/shimmie2-Material-Theme/tree/Material_-_Home)

**Comment by dali99** [comment]
Never mind, found it, it's in ext\bbcode\main.php:41
Some fancy regex.
Im unsure how I could change this to only apply for front page and this theme though

**Comment by dali99** [comment]
see #538 for a pull request implmenting the home extension

**Comment by shish** [comment]
This hasn't progressed in a while and I don't think there's more to do from this end, so closing for now, feel free to reopen if it's still relevant
