### ISSUE TITLE
Create tutorial/documentation for developing extensions and themes.

### ISSUE THREAD

**Issue by JarJak** [shish/shimmie2#521]
It would be nice if there will be any docs for shimmie developers, like how to create an extension, which events to hook, how to make it working with the framework.

**Comment by JarJak** [comment]
@shish

**Comment by shish** [comment]
It's somewhat out of date, but there is http://shimmie.shishnet.org/doc/ -- unit testing has changed almost completely, but the stuff about shimmie itself (pages, blocks, events) should be the same. Will leave this ticket open as a reminder to look through the docs and make sure they're up to date though, and also to add some tutorial-style stuff that explains how to create new stuff from scratch rather than just explaining the architecture :3

**Comment by JarJak** [comment]
Thanks, it's a nice entry point. It would be nice to see this docs on Github too, so it would be versionable etc.

**Comment by dali99** [comment]
I would love for a bit more documentation on extensions myself, a simple tutorial to understand the basics of what is possible.

**Comment by shish** [comment]
A bunch of docs got added into the repo itself now; closing this but feel free to ask more specific questions if more things are needed ^^
