### ISSUE TITLE
Multiple Shimmie installations under one domain

### ISSUE THREAD

**Issue by cyb-er** [shish/shimmie2#595]
I would like to have a few installations on same domain. One in the root of a domain and others in folders

Shimmie 1 -> example.com
Shimmie 2 -> example.com/shimmie2/
Shimmie 3 -> example.com/shimmie3/

Same design (just a different logo), same extensions, admin settings.. Just different databases and media content (pictures).

Currently I’ve just run tests by simply installing Shimmie to those sub-folders and I’ve changed the cookie prefix in the config file for each sub-site. It seems to work. Though, I have thought that I will ask here if there is anything I should pay attention to in order to avoid conflicts? I would be grateful for any suggestions/feedback. 

And on a side note, if anyone else done something like that before and doesn’t mind sharing the info it would be really cool. I was wondering if perhaps those sub shimmie sites could operate on same files that are located in the root. I understand there would still be a need for a few customized php files in sub-sites e.g. index.php and the config files.

**Comment by shish** [comment]
Multiple installs side-by-side work fine - overlapping (eg one at the top level of the domain and one in a subfolder) might get confusing as shimmie expects to control all of its own sub-folders; but I expect it would work with some web server configuring (eg in the root folder, rather than "have shimmie handle all requests", configure it for "have shimmie handle everything except /shimmie2 and /shimmie3" - how to exactly do that would depend on the web server)

Sharing source code across installs is something I've considered - it would need a bunch of work, but it's not fundamentally impossible...

**Comment by cyb-er** [comment]
I've just added the exception rule into the top Shimmie site's htaccess file for those 2 sub folder.
All seems to work fine. Thank you! :+1:
