### ISSUE TITLE
Tags containing underscores cannot be searched.

### ISSUE THREAD

**Issue by needed-a-name** [shish/shimmie2#619]
I'm running the 2.6.0 release.
As the title says if an image is tagged with something containing an underscore such as test_tag and a search performed for that tag the booru reports no results.

**Comment by RaZZlom** [comment]
2.6.2 The same bug

**Comment by muhkuh2005** [comment]
Works fine with me.
Got several images tagged *original_characer*.
When I search for *original_character* they are listed as expected.
Testenvironment:
Apache 2
PHP 7.0.27
shimmie 2.6.2 (worked on 2.5.1 too, just upgraded)

Note: Keep in mind that underscores are replaced by spaces (Maybe something went wrong when saving the tag? Does the Taglist of the images tagged with the underscored-tag show it with an space or underscore?

**Comment by billsargent** [comment]
I'm having the same problem on a new install using sqlite3 ... i switched to sqlite because mysql was jamming up on a join statement when the database got really large.

**Comment by DanielOaks** [comment]
Hmm, I'm running into this issue from a new install of `develop`. The issue seems to be that SQLite specifically decides to not use the escaping that's automagically applied by `Tag::sqlify`, [this page](https://www.sqlite.org/lang_expr.html) says _"C-style escapes using the backslash character are not supported because they are not standard SQL."_

That same page also mentions that the SQLite `ESCAPE` clause does enable the sort of escaping that shimmie expects from its db, so that might be useful in solving this. I'll have a play and see where I can get!
