### ISSUE TITLE
Swapped hosts - all images now corrupt

### ISSUE THREAD

**Issue by ViperThreat** [shish/shimmie2#635]
Did a simple FTP transfer, thumbnails seem to have survived, but full resolution images seem to be corrupt - unable to load them in any image program, file repair utilities unsuccessful.

Any ideas?

**Comment by shish** [comment]
The most common cause of corruption during FTP transfers is if your FTP software is set to "text" mode instead of "binary" mode (binary = transfer the files as they are without touching them, text = attempt to do weird magic and corrupt anything that's not a .txt file). Weird that thumbnails survived though...

Either way, Shimmie just serves up the files that are on disk, so if they're corrupt on disk, there's nothing that can be done to fix that :(
