### ISSUE TITLE
Video thumbnails with ffmpeg are 1:1 even with ignore true

### ISSUE THREAD

**Issue by jackr579** [shish/shimmie2#637]
i am using the march 17 2018 static build of ffmpeg for windows and have created a Path dir to the bin folder of ffmpeg, and referenced ffmpeg.exe in shimmie's board config. when regenerating video thumbnails with the ignore aspect option turned on, a thumbnail is never generated. With it turned on, the aspect ratio of the thumbnail is 1:1. Is there a way to make this thumbnail the same aspect as the video file itself?

**Comment by Apowerse** [comment]
Bit OT, What did you use as path in shimmie?

**Comment by PronMaster** [comment]
Hello any update on this I noticed Apowerse is using windows any fix for this on linux?

**Comment by shish** [comment]
This should be fixed now (as of a while ago, I just forgot to update all the bug reports) - the whole ffmpeg thumbnailing code got redone (now instead of using ffmpeg for generating a small image, we just use ffmpeg to pick one frame out of the video, and then we use the normal image thumbnailing code on that image)
