### ISSUE TITLE
Users keep getting logged out Bug

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#645]
Hello anyone have any solution for a bug where my users keep getting logged out its happening like every 30-seconds could this be a issue with .htacess file or the script or my server?

**Comment by arthurmv** [comment]
I had same problem but my booru is private, changing from Chrome to Firefox was the fix.

**Comment by PronMaster** [comment]
You saying your browser was your issue because I already tried chrome and firefox its the same issue.

**Comment by arthurmv** [comment]
I just said randomly log off me, but when I switch browser I fix it.

**Comment by shish** [comment]
The login cookie is associated with a particular IP range (so that stolen cookies are useless, as the thief's IP address would be different); which has the side effect that whenever a user changes IP to a new network, they'll need to log in again.

By default the sessions are masked with 255.255.0.0 (ie the last two parts of the IP are ignored, they only need to be on the same network). Going to advanced settings and setting `session_hash_mask` to `0.0.0.0`  should make it so that login cookies are valid anywhere, and people won't get logged out when they change networks.

If they're getting logged out while their IP is the same, then that's going to be something different and feel free to re-open and we can investigate more from there...
