### ISSUE TITLE
Is the current Branch (master) usable?

### ISSUE THREAD

**Issue by FlipperLP** [shish/shimmie2#806]
I tried to compile the master branch to a Docker image for quite some time now.
Is it meant for productivity use or the newest release the one in [Releases](https://github.com/shish/shimmie2/releases)?

**Comment by sanmadjack** [comment]
Pretty sure the docker setup in master is only for running tests, not for running a server.

**Comment by FlipperLP** [comment]
Yea the problem is debian:testing-slim is that there is currently a bug in the arm32v7 version of Debian (a GPG error that can't be resolved that easily)

But the question originally came up, because @shish has been working on if for the last couple of days, so I just wanted to check that.

**Comment by shish** [comment]
Master *should* be usable - it's more risky, just by way of changing more often and being based on more recent foundations - but if it doesn't work I'd still consider it a bug that needs fixing :)

**Comment by FlipperLP** [comment]
Any hint, when the next update is going to drop?

**Comment by shish** [comment]
There are updates all the time - is there something specific you're wanting to be updated? (The docker image? The .zip download? Debian arm? The master branch? The libraries? The base OS?)

If you send bug report details (what are you trying, what do you expect to happen, what actually happens, etc) then I could try fixing the problem -- right now all I know is "something somewhere is broken for someone" - if I don't know what the problem is, then I can't even guess when it'll get fixed ^^;

**Comment by FlipperLP** [comment]
It was more of a general question, no bug report as the problem isn't your fault.
