### ISSUE TITLE
mp4 unconsistently not uploading

### ISSUE THREAD

**Issue by laureegrd** [shish/shimmie2#821]
Uploading certain mp4 files will redirect to /upload without any error message. Trying to replace existing posts with those files will lead to similar results, only this time it will say the mp4 format is not supported.
It might be related to mime-types since running `file --mime-type file.mp4` on linux returns "video/x-m4v". Although I tried converting them to "video/mp4" with ffmpeg, some were able to upload after that, but most didn't work.

 - Shimmie version: 2.8.4+
 - Database: mysql 10.5.9-MariaDB
 - Web server: lighttpd/1.4.59

 - Browser: Firefox Desktop on Linux, Chrome on Android.

**What steps trigger this bug**
Explained above. It's hard to point out the exact problem since it is inconsistent with different .mp4 files.

**What did you expect to happen?**
All .mp4 files to upload without errors.

**Comment by LaureeGrd** [comment]
Just noticed 2.9.1 and updated. Problem persists.

**Comment by shish** [comment]
My first guess is that some of the files might be larger than what lighttpd allows, and so it's removing the files from the upload process before shimmie can see them...

Other than that, could any examples of working and not-working be shared to test with?

**Comment by LaureeGrd** [comment]
> My first guess is that some of the files might be larger than what lighttpd allows, and so it's removing the files from the upload process before shimmie can see them...
> 
> Other than that, could any examples of working and not-working be shared to test with?

It was simply the filesize. I remember checking error logs before but nothing was there. I checked again and php was complaining about exceeding POST size of 8MB. Is there any way we can improve this so that shimmie notifies the user that the POST request has exceeded the server's limit?

My guess is that the few videos that uploaded after conversion were just above 8MB and ffpmpeg was improving the filesize and I didn't notice the change...
