### ISSUE TITLE
How to migrate to another server

### ISSUE THREAD

**Issue by jkulzer** [shish/shimmie2#831]
I want to transfer shimmie from a Rasperry Pi to a new server. I am running Apache on both servers and I can install a new instance. How can I copy everything onto my new server?

**Comment by shish** [comment]
Probably the easiest way is to copy the whole folder - all the site-specific data would live in the `data` folder but no harm copying the software too; then copying the database depends on which database you use. If the new database lives somewhere different to the old one then you'd need to update the connection string in `data/config/shimmie.conf.php`

**Comment by Randomusername994** [comment]
I tried copying all files, creating a new instance and using the bulk import/export feature. However, the upload fails when I upload the exported zip. On Firefox it shows a blank page, on Chromium it gives an error 500. It is not "MIME type not supported: application/zip" when uploading a zip file without the export.json file. My Apache error logs show this message whenever I upload an exported zip. Normal pictures upload fine though. It also isn't a permission issue, I used chmod 777 and the error still persisted.

Here is the error message from the Apache error logs.

`[php:error] [pid 777] [client 192.168.178.22:34460] PHP Fatal error:  Uncaught TypeError: Cannot assign stdClass to property BulkImportEvent::$fields of type array in /var/www/html/shimmie2/ext/bulk_import_export/events.php:25\nStack trace:\n#0 /var/www/html/shimmie2/ext/bulk_import_export/main.php(67): BulkImportEvent->__construct()\n#1 /var/www/html/shimmie2/core/send_event.php(113): BulkImportExport->onDataUpload()\n#2 /var/www/html/shimmie2/ext/upload/main.php(355): send_event()\n#3 /var/www/html/shimmie2/ext/upload/main.php(236): Upload->try_upload()\n#4 /var/www/html/shimmie2/core/send_event.php(113): Upload->onPageRequest()\n#5 /var/www/html/shimmie2/index.php(82): send_event()\n#6 {main}\n  thrown in /var/www/html/shimmie2/ext/bulk_import_export/events.php on line 25, referer: http://192.168.178.34/shimmie2/index.php?q=upload
`

**Comment by Randomusername994** [comment]
I tried copying the whole folder and database and I can get the homepage , but when I do anything like searching or clicking on the logo I get a 404 Object not found error. However the login page loads, but I get a 404 error too when pressing the login button. The problem seems to be with the database.

`PHP Fatal error:  Uncaught SCoreException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shimmie.config' doesn't exist in /var/www/html/mybooru/core/database.php:184\nStack trace:\n#0 /var/www/html/mybooru/core/database.php(194): Database->execute()\n#1 /var/www/html/mybooru/core/config.php(298): Database->get_all()\n#2 /var/www/html/mybooru/index.php(46): DatabaseConfig->__construct()\n#3 {main}\n  thrown in /var/www/html/mybooru/core/database.php on line 184
`

**Comment by shish** [comment]
Looks like the database didn't get copied across; I'm assuming this is either fixed or abandoned, feel free to comment if it's still an issue ^^;
