### ISSUE TITLE
Forum extension dosn't handle (some?) special characters right

### ISSUE THREAD

**Issue by PVNFU-28** [shish/shimmie2#835]
**Server Software**
 - Shimmie version: 2.9.1+
 - PHP: 7.4.3
 - Database: MySQL 8.0.25
 - Web server: Apache 2.4.41

**Client Software (please complete the following information)**
 - Device: Windows laptop
 - Browser: Chrome

**What steps trigger this bug**
1. Go to https://carbu.tk/forum/view/1/1
2. make a post containing the character ' or watch the previously created one containing said bug

**What did you expect to happen?**
I expected the ' so show up as '

**What actually happened?**
Instead, it showed up as \&#039;

Is this a bug or intended?

**Comment by loudhouse** [comment]
I am also having this issue. It only seems to affect some special characters - in particular the one mentioned in the OP, which is particularly annoying in forum posts as plurals are often used. 

It also seems to affect the extensions list (so it cannot be an issue with the forum extension specifically) - for example the description of the 'head' extension shows up as ``Allows admins to modify & set custom &lt;head&gt; content`` instead of "<head>". 

There was never any follow up to OP's original issue - any ideas what might be going on here?
