### ISSUE TITLE
Make Anonymous users unable to view any images, tags or image thumbnails

### ISSUE THREAD

**Issue by jovianArchiver** [shish/shimmie2#843]
I'd like to make only users to be able to see the proper site, is there a tag that either allows me to remove anon users' ability to view posts, tag lists, etc? If not, would it be possible to implement it?

**Comment by MetallicAchu** [comment]
On the control panel, you should have options to choose which users can view what, it’s usually for sensitive content but it should be useable in your case as well. 

There are 4 ratings: Unrated, Safe, Questionable and Explicit
You can choose that guests are able to only view safe / unrated, and mark everything on your gallery to something else, thus mandating a user register in order to view anything.

**Comment by jovianArchiver** [comment]
Where in the control panel is that option? I can't find a response on the wiki.

**Comment by MetallicAchu** [comment]
> Where in the control panel is that option? I can't find a response on the wiki. Also, would this prevent anons from seeing the tags list?
> 
> EDIT: I found it, you need to install the Post Ratings extension and then there's a Post Ratings menu on the Board Config page on the bottom right.

That's right. Did it work for you?
You can also activate the "bulk actions" extension and change the rating for multiple pictures as once.

If this solution works for you please close the issue

**Comment by ddomino007** [comment]
IIRC You can disallow anonymous to browse even rating:safe so using something else just to hide images from unregistered shouldn't be needed

**Comment by Giraffaman** [comment]
> IIRC You can disallow anonymous to browse even rating:safe so using something else just to hide images from unregistered shouldn't be needed

to elaborate on this for anyone looking for it: 
to prevent a user group from seeing _any_ posts regardless of the rating, go to Board Config > Advanced and find the ext_rating_<usergroup> setting you want, then clear the setting. I'm adding this because I didn't find a way to do this in the "simple" board config's menu (selecting none of the ratings under "Post Rating Visibility" will turn to "all selected once your save and reload the config page.

**Comment by Giraffaman** [comment]
just saw in /ext/rating/main.php that it looks for and, if present, includes `data/config/ratings.conf.php`. So my solution now is to add a "public" rating to be used only for posts which should be seen by anonymous/ghost users:
```
<?php
namespace Shimmie2;

add_rating(new ImageRating("p", "PUBLIC", "public", 90000));
```
afaik the number 90000 just determines the order in which the rating is shown in the board settings > post ratings menu.

I have set anonymous and ghost users to only be allowed to see this rating, so now they don't even see unrated posts. Nice.
