### ISSUE TITLE
MIME types and nice URLs on LiteSpeed

### ISSUE THREAD

**Issue by Dadealos** [shish/shimmie2#855]
Running Shimmie 2.9.1 on LiteSpeed 6.0.11

Using the included .htaccess and nice URLs, it works mostly fine. However, if I try to directly access a file (e.g. right click and "open image in new tab"), Chrome will render an image as text (with MIME type application/octet-stream). Firefox seems work fine.

This is running on a shared host and I don't have access to the logs. I was eventually able to get it working by adding rewrite rules that forced MIME type based on the requested extension. Like:

```
RewriteRule (.*\.jpg)$ $1 [T=image/jpeg]
RewriteRule ^_(images|thumbs)/([0-9a-f]{2})([0-9a-f]{30}).*$  data/$1/$2/$2$3 [L]
```

Is there a better way to do this? I've been reading through the Apache/LiteSpeed docs and I'm completely lost.

**Comment by shish** [comment]
It's been a long time since I did anything with apache, and never touched litespeed, but what you have there looks as good as I can imagine it getting -- with nice URLs enabled shimmie itself gets out of the way and lets the web server serve things directly, and AFAIK rewrite rules in .htaccess is the only way to control how it does that
