### ISSUE TITLE
Docker GID error

### ISSUE THREAD

**Issue by arthurmv** [shish/shimmie2#896]
[Docker image](https://hub.docker.com/r/shish2k/shimmie2)
My GID: 100

    groupadd: GID '100' already exists
    mkdir: cannot create directory '/app/data': File exists
    chown: invalid group: 'shimmie:shimmie'
    su-exec: getgrnam(shimmie): Success

Everytime when I got an update I have to change the GID var to 1000, turn on the container, wait few seconds, turn off container, return the value to 100 and turn it on again.

**Comment by shish** [comment]
Making some assumptions here:
- You're using the docker CLI flags to set UID/GID to 100, because that matches your desktop user outside of docker, and you want shimmie files to be owned by your user?
- Shimmie will create a new user when the container is launched
- The base debian image inside the container already has a user with UID 100 (`messagebus`) - IIRC debian considers UIDs 0 to 999 to be reserved for system use

I'm not sure how your workaround avoids that o_O

I'm also not sure what is a good solution for "user wants to specify a UID which is already allocated inside the container OS"...

**Comment by arthurmv** [comment]
> * You're using the docker CLI flags to set UID/GID to 100, because that matches your desktop user outside of docker, and you want shimmie files to be owned by your user?

Yes, my UID is fine, the issue is setting the GID value to match my NAS user.

> * The base debian image inside the container already has a user with UID 100 (messagebus) - IIRC debian considers UIDs 0 to 999 to be reserved for system use

> I'm also not sure what is a good solution for "user wants to specify a UID which is already allocated inside the container OS"...

My user on NAS has UID value above 1000.

**Comment by shish** [comment]
Wait, so, what docker command line are you using?

**Comment by arthurmv** [comment]
In order to do container editions I use [Synology Docker](https://www.synology.com/en-us/dsm/packages/Docker). For everything else I use [Portainer](https://www.portainer.io/).

**Comment by arthurmv** [comment]
Docker composer

    version: "3.6"
    services:
      booru:
        command:
          - /bin/sh
          - /app/tests/docker-init.sh
        container_name: booru
        environment:
          - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          - UID=1001
          - GID=100
        hostname: booru
        image: shish2k/shimmie2:latest
        ipc: private
        logging:
          driver: db
          options: {}
        network_mode: bridge
        ports:
          - 8000:8000/tcp
        stdin_open: true
        tty: true
        volumes:
          - /volume1/docker/booru:/app/data
        working_dir: /app

**Comment by shish** [comment]
4e6481d3 is horrible, but it should work. In general if you're trying to use an ID which is already in use by the system for other purposes, you're going to have a bad time ^^;;
