### ISSUE TITLE
Add an option to blur thumbnails of questionable/explicit images

### ISSUE THREAD

**Issue by Ayutac** [shish/shimmie2#910]
Add an option to blur thumbnails of questionable/explicit images to user profile, or alternatively to a user class.

I'm in charge of a booru that has both sfw and nsfw entries and I would like to automatically blur the nsfw thumbnails. Actually have done that with css already, but globally. Now an adult is complaining about the blur, so I would like to remove it per user or per user class.

**Comment by shish** [comment]
The first way that comes to mind for doing this would be to add the user's class name into the css of the `<body>` tag (eg `<body class="userclass-admin">`), and then have different CSS rules apply for `BODY.userclass-admin` and `BODY.userclass-adult` etc

I'm not sure how to do this in a generic way that works for all use-cases, but having some individual parts upstream (eg the css class on the body tag) seems reasonable if that turns out to be useful in helping you to build something that works for your use-case :3

**Comment by tegaki-tegaki** [comment]
This feels very similar to the Ratings extension:

<img width="592" alt="image" src="https://github.com/shish/shimmie2/assets/30883638/beac2533-fec1-49b8-89b4-fa3acb74a0b3">

but instead of blurring it hides, and instead of "adult" it's more permission based types (admin, anon...) 🤔

**Comment by shish** [comment]
74fd48a0 adds `data-userclass="..."` to the BODY tag, so that one can apply any style to any user/tag/rating/etc combination like:

```
BODY[data-userclass="anonymous"] .thumb[data-rating="e"] IMG {
    filter: blur(5px);
}
```

(if somebody has an idea for how to do this in an elegant GUI way feel free to describe in a new issue / PR. My gut says that use-cases would be fairly varied, with the easiest sufficiently-flexible thing being a "stick an arbitrary blob of CSS in the header" extension...)
