### ISSUE TITLE
Apache Dockerfile

### ISSUE THREAD

**Issue by intergalacticmonkey** [shish/shimmie2#965]
I created a Dockerfile which builds a Shimmie + PHP + Apache + SQLite container: https://github.com/intergalacticmonkey/shimmie2-apache-docker/

If you'd like to include or link to it in the [Shimmie docs](https://github.com/shish/shimmie2/wiki/Apache), it might be helpful for those wishing to run Shimmie on Apache in Docker.

Aside: Shimmie is awesome, thanks for your work!

**Comment by shish** [comment]
Ooh, that is nice :D

I have been thinking it'd be nice if the official shimmie docker image was based on a real web server but couldn't quite get all the things to work together (the web server itself, extra PHP modules, web server config like upload limits, system user IDs and permissions, etc) - but I was mostly trying nginx since that's what I'm most familiar with, maybe apache would actually work better 🤔

**Comment by shish** [comment]
The link got added to the docs, and as of 282d13f6 the container is using a Real Web Server (nginx unit, because that seems to work particularly nicely with containers)
